spring.application.name=iyunga-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/iyunga_db
spring.datasource.username=postgres
spring.datasource.password=Sanga@19
spring.jpa.hibernate.ddl-auto=update